import { Component, Host, h } from '@stencil/core';
import state from '../../app/globalStore';

@Component({
  tag: 'twui-privacy',
  shadow: false,
})
export class TWUIPrivacy {
  render() {
    return (
      <Host class="page">
        <section>
          <twui-text format="header">{state.dictionary.strings.pages.privacy.title}</twui-text>
          <twui-text format="secondary">{state.dictionary.strings.pages.privacy.subtitle}</twui-text>
        </section>

        <twui-card label="What is TaleWeaver?" icon="mingcute:question-fill">
          <twui-text format="secondary">
            TaleWeaver is an AI-powered bedtime story application designed specifically for children ages 3-8. We create magical, personalized stories while keeping your family's
            privacy completely secure.
          </twui-text>
        </twui-card>

        <twui-card label="Data Collection" icon="mdi:book-secure">
          <twui-infobox
            slot="beforecontent"
            icon="tdesign:user-blocked-filled"
            label="Zero Personal Data Collection"
            message="We do NOT collect, store, or share any personal information about children."
          ></twui-infobox>
          <twui-text format="subheading">What stays on your device</twui-text>
          <ul>
            <li>Child's name and age (if you provide it)</li>
            <li>Story preferences and themes</li>
            <li>App settings</li>
            <li>Generated story history</li>
          </ul>
          <twui-text format="subheading">What we send for story generation</twui-text>
          <ul>
            <li>Anonymous story themes (e.g., "adventure," "animals")</li>
            <li>Age-appropriate content guidelines</li>
            <li>NO personal names, locations, or identifying information</li>
          </ul>
        </twui-card>

        <twui-card label="Parental Control" icon="fluent-mdl2:family">
          <twui-text format="subheading">You are in complete control</twui-text>
          <ul>
            <li>Only parents can make purchases or manage settings</li>
            <li>Children cannot submit personal information</li>
            <li>All sensitive actions are protected by parental gates</li>
            <li>All data stays on your device</li>
          </ul>
        </twui-card>

        <twui-card label="Third-Party Services" icon="hugeicons:connect">
          <twui-text format="subheading">We use these services for app functionality</twui-text>
          <ul>
            <li>OpenAI API: For AI story generation (anonymized prompts only)</li>
            <li>ElevenLabs API: For voice synthesis (text-to-speech only)</li>
          </ul>
          <twui-text format="subheading">We do NOT use</twui-text>
          <ul>
            <li>Analytics or tracking services</li>
            <li>Advertising networks</li>
            <li>Social media integrations</li>
            <li>Any services that collect personal data</li>
          </ul>
        </twui-card>

        <twui-card label="Content Safety" icon="ant-design:safety-outlined">
          <twui-text format="subheading">All stories generated by TaleWeaver are:</twui-text>
          <ul>
            <li>Filtered for family-friendly content</li>
            <li>Designed for children ages 3-8</li>
            <li>Free from violence, inappropriate themes, or scary content</li>
            <li>Supervised by AI safety guidelines specifically designed for children</li>
          </ul>
          <twui-infobox
            slot="aftercontent"
            icon="fluent-mdl2:family"
            label="Parent Supervision Recommended"
            message="While our AI is designed to generate safe content, we recommend parents preview stories for younger children."
            color="warning"
          ></twui-infobox>
        </twui-card>

        <twui-button iconbefore="cil:send" label="Contact Privacy Team"></twui-button>
        <twui-text format="secondary" align="center">
          We respond to all privacy inquiries within 48 hours.
        </twui-text>
      </Host>
    );
  }
}
