/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TwuiAccordion {
        "icon"?: string;
        "label"?: string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface TwuiApp {
    }
    interface TwuiButton {
        "color"?: 'secondary' | 'link';
        "iconafter"?: string;
        "iconbefore"?: string;
        "label"?: string;
        /**
          * @default 'button'
         */
        "type"?: string;
    }
    interface TwuiCard {
        /**
          * @default true
         */
        "filled"?: boolean;
        "icon"?: string;
        "label"?: string;
    }
    interface TwuiCreatestory {
    }
    interface TwuiGrid {
        "icon"?: string;
        "label"?: string;
    }
    interface TwuiGriditem {
        /**
          * optional icon
         */
        "icon"?: string;
        /**
          * optional label
         */
        "label"?: string;
    }
    interface TwuiHeader {
    }
    interface TwuiInfobox {
        "color"?: 'success' | 'warning' | 'error';
        "icon"?: string;
        "label"?: string;
        "message"?: string;
    }
    interface TwuiNav {
    }
    interface TwuiOnboarding {
    }
    interface TwuiPagecontainer {
    }
    interface TwuiParentallock {
    }
    interface TwuiPrivacy {
    }
    interface TwuiProfile {
    }
    interface TwuiSettings {
    }
    interface TwuiText {
        "align"?: 'center' | 'right';
        "format"?: 'header' | 'subheading' | 'secondary';
    }
    interface TwuiUpgrade {
    }
}
declare global {
    interface HTMLTwuiAccordionElement extends Components.TwuiAccordion, HTMLStencilElement {
    }
    var HTMLTwuiAccordionElement: {
        prototype: HTMLTwuiAccordionElement;
        new (): HTMLTwuiAccordionElement;
    };
    interface HTMLTwuiAppElement extends Components.TwuiApp, HTMLStencilElement {
    }
    var HTMLTwuiAppElement: {
        prototype: HTMLTwuiAppElement;
        new (): HTMLTwuiAppElement;
    };
    interface HTMLTwuiButtonElement extends Components.TwuiButton, HTMLStencilElement {
    }
    var HTMLTwuiButtonElement: {
        prototype: HTMLTwuiButtonElement;
        new (): HTMLTwuiButtonElement;
    };
    interface HTMLTwuiCardElement extends Components.TwuiCard, HTMLStencilElement {
    }
    var HTMLTwuiCardElement: {
        prototype: HTMLTwuiCardElement;
        new (): HTMLTwuiCardElement;
    };
    interface HTMLTwuiCreatestoryElement extends Components.TwuiCreatestory, HTMLStencilElement {
    }
    var HTMLTwuiCreatestoryElement: {
        prototype: HTMLTwuiCreatestoryElement;
        new (): HTMLTwuiCreatestoryElement;
    };
    interface HTMLTwuiGridElement extends Components.TwuiGrid, HTMLStencilElement {
    }
    var HTMLTwuiGridElement: {
        prototype: HTMLTwuiGridElement;
        new (): HTMLTwuiGridElement;
    };
    interface HTMLTwuiGriditemElement extends Components.TwuiGriditem, HTMLStencilElement {
    }
    var HTMLTwuiGriditemElement: {
        prototype: HTMLTwuiGriditemElement;
        new (): HTMLTwuiGriditemElement;
    };
    interface HTMLTwuiHeaderElement extends Components.TwuiHeader, HTMLStencilElement {
    }
    var HTMLTwuiHeaderElement: {
        prototype: HTMLTwuiHeaderElement;
        new (): HTMLTwuiHeaderElement;
    };
    interface HTMLTwuiInfoboxElement extends Components.TwuiInfobox, HTMLStencilElement {
    }
    var HTMLTwuiInfoboxElement: {
        prototype: HTMLTwuiInfoboxElement;
        new (): HTMLTwuiInfoboxElement;
    };
    interface HTMLTwuiNavElement extends Components.TwuiNav, HTMLStencilElement {
    }
    var HTMLTwuiNavElement: {
        prototype: HTMLTwuiNavElement;
        new (): HTMLTwuiNavElement;
    };
    interface HTMLTwuiOnboardingElement extends Components.TwuiOnboarding, HTMLStencilElement {
    }
    var HTMLTwuiOnboardingElement: {
        prototype: HTMLTwuiOnboardingElement;
        new (): HTMLTwuiOnboardingElement;
    };
    interface HTMLTwuiPagecontainerElement extends Components.TwuiPagecontainer, HTMLStencilElement {
    }
    var HTMLTwuiPagecontainerElement: {
        prototype: HTMLTwuiPagecontainerElement;
        new (): HTMLTwuiPagecontainerElement;
    };
    interface HTMLTwuiParentallockElement extends Components.TwuiParentallock, HTMLStencilElement {
    }
    var HTMLTwuiParentallockElement: {
        prototype: HTMLTwuiParentallockElement;
        new (): HTMLTwuiParentallockElement;
    };
    interface HTMLTwuiPrivacyElement extends Components.TwuiPrivacy, HTMLStencilElement {
    }
    var HTMLTwuiPrivacyElement: {
        prototype: HTMLTwuiPrivacyElement;
        new (): HTMLTwuiPrivacyElement;
    };
    interface HTMLTwuiProfileElement extends Components.TwuiProfile, HTMLStencilElement {
    }
    var HTMLTwuiProfileElement: {
        prototype: HTMLTwuiProfileElement;
        new (): HTMLTwuiProfileElement;
    };
    interface HTMLTwuiSettingsElement extends Components.TwuiSettings, HTMLStencilElement {
    }
    var HTMLTwuiSettingsElement: {
        prototype: HTMLTwuiSettingsElement;
        new (): HTMLTwuiSettingsElement;
    };
    interface HTMLTwuiTextElement extends Components.TwuiText, HTMLStencilElement {
    }
    var HTMLTwuiTextElement: {
        prototype: HTMLTwuiTextElement;
        new (): HTMLTwuiTextElement;
    };
    interface HTMLTwuiUpgradeElement extends Components.TwuiUpgrade, HTMLStencilElement {
    }
    var HTMLTwuiUpgradeElement: {
        prototype: HTMLTwuiUpgradeElement;
        new (): HTMLTwuiUpgradeElement;
    };
    interface HTMLElementTagNameMap {
        "twui-accordion": HTMLTwuiAccordionElement;
        "twui-app": HTMLTwuiAppElement;
        "twui-button": HTMLTwuiButtonElement;
        "twui-card": HTMLTwuiCardElement;
        "twui-createstory": HTMLTwuiCreatestoryElement;
        "twui-grid": HTMLTwuiGridElement;
        "twui-griditem": HTMLTwuiGriditemElement;
        "twui-header": HTMLTwuiHeaderElement;
        "twui-infobox": HTMLTwuiInfoboxElement;
        "twui-nav": HTMLTwuiNavElement;
        "twui-onboarding": HTMLTwuiOnboardingElement;
        "twui-pagecontainer": HTMLTwuiPagecontainerElement;
        "twui-parentallock": HTMLTwuiParentallockElement;
        "twui-privacy": HTMLTwuiPrivacyElement;
        "twui-profile": HTMLTwuiProfileElement;
        "twui-settings": HTMLTwuiSettingsElement;
        "twui-text": HTMLTwuiTextElement;
        "twui-upgrade": HTMLTwuiUpgradeElement;
    }
}
declare namespace LocalJSX {
    interface TwuiAccordion {
        "icon"?: string;
        "label"?: string;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface TwuiApp {
    }
    interface TwuiButton {
        "color"?: 'secondary' | 'link';
        "iconafter"?: string;
        "iconbefore"?: string;
        "label"?: string;
        /**
          * @default 'button'
         */
        "type"?: string;
    }
    interface TwuiCard {
        /**
          * @default true
         */
        "filled"?: boolean;
        "icon"?: string;
        "label"?: string;
    }
    interface TwuiCreatestory {
    }
    interface TwuiGrid {
        "icon"?: string;
        "label"?: string;
    }
    interface TwuiGriditem {
        /**
          * optional icon
         */
        "icon"?: string;
        /**
          * optional label
         */
        "label"?: string;
    }
    interface TwuiHeader {
    }
    interface TwuiInfobox {
        "color"?: 'success' | 'warning' | 'error';
        "icon"?: string;
        "label"?: string;
        "message"?: string;
    }
    interface TwuiNav {
    }
    interface TwuiOnboarding {
    }
    interface TwuiPagecontainer {
    }
    interface TwuiParentallock {
    }
    interface TwuiPrivacy {
    }
    interface TwuiProfile {
    }
    interface TwuiSettings {
    }
    interface TwuiText {
        "align"?: 'center' | 'right';
        "format"?: 'header' | 'subheading' | 'secondary';
    }
    interface TwuiUpgrade {
    }
    interface IntrinsicElements {
        "twui-accordion": TwuiAccordion;
        "twui-app": TwuiApp;
        "twui-button": TwuiButton;
        "twui-card": TwuiCard;
        "twui-createstory": TwuiCreatestory;
        "twui-grid": TwuiGrid;
        "twui-griditem": TwuiGriditem;
        "twui-header": TwuiHeader;
        "twui-infobox": TwuiInfobox;
        "twui-nav": TwuiNav;
        "twui-onboarding": TwuiOnboarding;
        "twui-pagecontainer": TwuiPagecontainer;
        "twui-parentallock": TwuiParentallock;
        "twui-privacy": TwuiPrivacy;
        "twui-profile": TwuiProfile;
        "twui-settings": TwuiSettings;
        "twui-text": TwuiText;
        "twui-upgrade": TwuiUpgrade;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "twui-accordion": LocalJSX.TwuiAccordion & JSXBase.HTMLAttributes<HTMLTwuiAccordionElement>;
            "twui-app": LocalJSX.TwuiApp & JSXBase.HTMLAttributes<HTMLTwuiAppElement>;
            "twui-button": LocalJSX.TwuiButton & JSXBase.HTMLAttributes<HTMLTwuiButtonElement>;
            "twui-card": LocalJSX.TwuiCard & JSXBase.HTMLAttributes<HTMLTwuiCardElement>;
            "twui-createstory": LocalJSX.TwuiCreatestory & JSXBase.HTMLAttributes<HTMLTwuiCreatestoryElement>;
            "twui-grid": LocalJSX.TwuiGrid & JSXBase.HTMLAttributes<HTMLTwuiGridElement>;
            "twui-griditem": LocalJSX.TwuiGriditem & JSXBase.HTMLAttributes<HTMLTwuiGriditemElement>;
            "twui-header": LocalJSX.TwuiHeader & JSXBase.HTMLAttributes<HTMLTwuiHeaderElement>;
            "twui-infobox": LocalJSX.TwuiInfobox & JSXBase.HTMLAttributes<HTMLTwuiInfoboxElement>;
            "twui-nav": LocalJSX.TwuiNav & JSXBase.HTMLAttributes<HTMLTwuiNavElement>;
            "twui-onboarding": LocalJSX.TwuiOnboarding & JSXBase.HTMLAttributes<HTMLTwuiOnboardingElement>;
            "twui-pagecontainer": LocalJSX.TwuiPagecontainer & JSXBase.HTMLAttributes<HTMLTwuiPagecontainerElement>;
            "twui-parentallock": LocalJSX.TwuiParentallock & JSXBase.HTMLAttributes<HTMLTwuiParentallockElement>;
            "twui-privacy": LocalJSX.TwuiPrivacy & JSXBase.HTMLAttributes<HTMLTwuiPrivacyElement>;
            "twui-profile": LocalJSX.TwuiProfile & JSXBase.HTMLAttributes<HTMLTwuiProfileElement>;
            "twui-settings": LocalJSX.TwuiSettings & JSXBase.HTMLAttributes<HTMLTwuiSettingsElement>;
            "twui-text": LocalJSX.TwuiText & JSXBase.HTMLAttributes<HTMLTwuiTextElement>;
            "twui-upgrade": LocalJSX.TwuiUpgrade & JSXBase.HTMLAttributes<HTMLTwuiUpgradeElement>;
        }
    }
}
