/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TwuiApp {
    }
    interface TwuiButton {
        "icon"?: string;
        "label"?: string;
        /**
          * @default 'button'
         */
        "type"?: string;
    }
    interface TwuiCustomstory {
    }
    interface TwuiHeader {
    }
    interface TwuiNav {
    }
    interface TwuiOnboarding {
    }
    interface TwuiPagecontainer {
    }
    interface TwuiParentallock {
    }
    interface TwuiPrivacy {
    }
    interface TwuiProfile {
    }
    interface TwuiQuickstory {
    }
    interface TwuiSettings {
    }
    interface TwuiText {
        "format"?: 'header' | 'hint';
    }
    interface TwuiUpgrade {
    }
}
declare global {
    interface HTMLTwuiAppElement extends Components.TwuiApp, HTMLStencilElement {
    }
    var HTMLTwuiAppElement: {
        prototype: HTMLTwuiAppElement;
        new (): HTMLTwuiAppElement;
    };
    interface HTMLTwuiButtonElement extends Components.TwuiButton, HTMLStencilElement {
    }
    var HTMLTwuiButtonElement: {
        prototype: HTMLTwuiButtonElement;
        new (): HTMLTwuiButtonElement;
    };
    interface HTMLTwuiCustomstoryElement extends Components.TwuiCustomstory, HTMLStencilElement {
    }
    var HTMLTwuiCustomstoryElement: {
        prototype: HTMLTwuiCustomstoryElement;
        new (): HTMLTwuiCustomstoryElement;
    };
    interface HTMLTwuiHeaderElement extends Components.TwuiHeader, HTMLStencilElement {
    }
    var HTMLTwuiHeaderElement: {
        prototype: HTMLTwuiHeaderElement;
        new (): HTMLTwuiHeaderElement;
    };
    interface HTMLTwuiNavElement extends Components.TwuiNav, HTMLStencilElement {
    }
    var HTMLTwuiNavElement: {
        prototype: HTMLTwuiNavElement;
        new (): HTMLTwuiNavElement;
    };
    interface HTMLTwuiOnboardingElement extends Components.TwuiOnboarding, HTMLStencilElement {
    }
    var HTMLTwuiOnboardingElement: {
        prototype: HTMLTwuiOnboardingElement;
        new (): HTMLTwuiOnboardingElement;
    };
    interface HTMLTwuiPagecontainerElement extends Components.TwuiPagecontainer, HTMLStencilElement {
    }
    var HTMLTwuiPagecontainerElement: {
        prototype: HTMLTwuiPagecontainerElement;
        new (): HTMLTwuiPagecontainerElement;
    };
    interface HTMLTwuiParentallockElement extends Components.TwuiParentallock, HTMLStencilElement {
    }
    var HTMLTwuiParentallockElement: {
        prototype: HTMLTwuiParentallockElement;
        new (): HTMLTwuiParentallockElement;
    };
    interface HTMLTwuiPrivacyElement extends Components.TwuiPrivacy, HTMLStencilElement {
    }
    var HTMLTwuiPrivacyElement: {
        prototype: HTMLTwuiPrivacyElement;
        new (): HTMLTwuiPrivacyElement;
    };
    interface HTMLTwuiProfileElement extends Components.TwuiProfile, HTMLStencilElement {
    }
    var HTMLTwuiProfileElement: {
        prototype: HTMLTwuiProfileElement;
        new (): HTMLTwuiProfileElement;
    };
    interface HTMLTwuiQuickstoryElement extends Components.TwuiQuickstory, HTMLStencilElement {
    }
    var HTMLTwuiQuickstoryElement: {
        prototype: HTMLTwuiQuickstoryElement;
        new (): HTMLTwuiQuickstoryElement;
    };
    interface HTMLTwuiSettingsElement extends Components.TwuiSettings, HTMLStencilElement {
    }
    var HTMLTwuiSettingsElement: {
        prototype: HTMLTwuiSettingsElement;
        new (): HTMLTwuiSettingsElement;
    };
    interface HTMLTwuiTextElement extends Components.TwuiText, HTMLStencilElement {
    }
    var HTMLTwuiTextElement: {
        prototype: HTMLTwuiTextElement;
        new (): HTMLTwuiTextElement;
    };
    interface HTMLTwuiUpgradeElement extends Components.TwuiUpgrade, HTMLStencilElement {
    }
    var HTMLTwuiUpgradeElement: {
        prototype: HTMLTwuiUpgradeElement;
        new (): HTMLTwuiUpgradeElement;
    };
    interface HTMLElementTagNameMap {
        "twui-app": HTMLTwuiAppElement;
        "twui-button": HTMLTwuiButtonElement;
        "twui-customstory": HTMLTwuiCustomstoryElement;
        "twui-header": HTMLTwuiHeaderElement;
        "twui-nav": HTMLTwuiNavElement;
        "twui-onboarding": HTMLTwuiOnboardingElement;
        "twui-pagecontainer": HTMLTwuiPagecontainerElement;
        "twui-parentallock": HTMLTwuiParentallockElement;
        "twui-privacy": HTMLTwuiPrivacyElement;
        "twui-profile": HTMLTwuiProfileElement;
        "twui-quickstory": HTMLTwuiQuickstoryElement;
        "twui-settings": HTMLTwuiSettingsElement;
        "twui-text": HTMLTwuiTextElement;
        "twui-upgrade": HTMLTwuiUpgradeElement;
    }
}
declare namespace LocalJSX {
    interface TwuiApp {
    }
    interface TwuiButton {
        "icon"?: string;
        "label"?: string;
        /**
          * @default 'button'
         */
        "type"?: string;
    }
    interface TwuiCustomstory {
    }
    interface TwuiHeader {
    }
    interface TwuiNav {
    }
    interface TwuiOnboarding {
    }
    interface TwuiPagecontainer {
    }
    interface TwuiParentallock {
    }
    interface TwuiPrivacy {
    }
    interface TwuiProfile {
    }
    interface TwuiQuickstory {
    }
    interface TwuiSettings {
    }
    interface TwuiText {
        "format"?: 'header' | 'hint';
    }
    interface TwuiUpgrade {
    }
    interface IntrinsicElements {
        "twui-app": TwuiApp;
        "twui-button": TwuiButton;
        "twui-customstory": TwuiCustomstory;
        "twui-header": TwuiHeader;
        "twui-nav": TwuiNav;
        "twui-onboarding": TwuiOnboarding;
        "twui-pagecontainer": TwuiPagecontainer;
        "twui-parentallock": TwuiParentallock;
        "twui-privacy": TwuiPrivacy;
        "twui-profile": TwuiProfile;
        "twui-quickstory": TwuiQuickstory;
        "twui-settings": TwuiSettings;
        "twui-text": TwuiText;
        "twui-upgrade": TwuiUpgrade;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "twui-app": LocalJSX.TwuiApp & JSXBase.HTMLAttributes<HTMLTwuiAppElement>;
            "twui-button": LocalJSX.TwuiButton & JSXBase.HTMLAttributes<HTMLTwuiButtonElement>;
            "twui-customstory": LocalJSX.TwuiCustomstory & JSXBase.HTMLAttributes<HTMLTwuiCustomstoryElement>;
            "twui-header": LocalJSX.TwuiHeader & JSXBase.HTMLAttributes<HTMLTwuiHeaderElement>;
            "twui-nav": LocalJSX.TwuiNav & JSXBase.HTMLAttributes<HTMLTwuiNavElement>;
            "twui-onboarding": LocalJSX.TwuiOnboarding & JSXBase.HTMLAttributes<HTMLTwuiOnboardingElement>;
            "twui-pagecontainer": LocalJSX.TwuiPagecontainer & JSXBase.HTMLAttributes<HTMLTwuiPagecontainerElement>;
            "twui-parentallock": LocalJSX.TwuiParentallock & JSXBase.HTMLAttributes<HTMLTwuiParentallockElement>;
            "twui-privacy": LocalJSX.TwuiPrivacy & JSXBase.HTMLAttributes<HTMLTwuiPrivacyElement>;
            "twui-profile": LocalJSX.TwuiProfile & JSXBase.HTMLAttributes<HTMLTwuiProfileElement>;
            "twui-quickstory": LocalJSX.TwuiQuickstory & JSXBase.HTMLAttributes<HTMLTwuiQuickstoryElement>;
            "twui-settings": LocalJSX.TwuiSettings & JSXBase.HTMLAttributes<HTMLTwuiSettingsElement>;
            "twui-text": LocalJSX.TwuiText & JSXBase.HTMLAttributes<HTMLTwuiTextElement>;
            "twui-upgrade": LocalJSX.TwuiUpgrade & JSXBase.HTMLAttributes<HTMLTwuiUpgradeElement>;
        }
    }
}
